version: '3.8'

networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: codechat_api
    image: codechat/api:v1.3.7
    restart: unless-stopped
    ports:
      - 8084:8084
    volumes:
      - instances_connected:/codechat/instances
      - /var/logs/codechat-api:/codechat/logs
    env_file:
      - ./.env
    networks:
      - public-network

volumes:
  # In terminal run: docker volume create --name=instances_connected
  instances_connected:
    external:
      name: instances_connected
